### ISSUE TITLE
Serial Communication

### ISSUE THREAD

**Issue by AndNing** [UWO-Aero-Design/gnd-station#6]
Send incoming and outgoing data to groundstation and database
- [x] Send data out
- [x] Retrieve data from radio

**Comment by cbaron3** [comment]
do you want the data parsed for this task?

**Comment by AndNing** [comment]
Yeah I guess here would be a good place to do it, then we only need to do it once per data.

**Comment by cbaron3** [comment]
started working on this on feature branch serial comms (feature/serial-comms)

**Comment by cbaron3** [comment]
is the requirement both to read and write or just read? If I remember correctly. only receving is needed for the November deadline right?
